version: "3.5"

services:
  raft-agent-0: 
    image: raft-image
    container_name: d0
    restart: "no"
    environment:
      - CONTAINER_NAME=d0
    build:
      context: .
    networks:
      - raft-network
    command: "-h=hostfile.txt -t=${PRJ2_TEST_CASE} -d=${PRJ2_DURATION} -v=${PRJ2_VERBOSE} --tfrom=${PRJ2_TFROM} --ttil=${PRJ2_TTIL}"

  raft-agent-1: 
    image: raft-image
    container_name: d1
    restart: "no"
    environment:
      - CONTAINER_NAME=d1
    build:
      context: .
    networks:
      - raft-network
    command: "-h=hostfile.txt -t=${PRJ2_TEST_CASE} -d=${PRJ2_DURATION} -v=${PRJ2_VERBOSE} --tfrom=${PRJ2_TFROM} --ttil=${PRJ2_TTIL}"

  raft-agent-2: 
    image: raft-image
    container_name: d2
    restart: "no"
    environment:
      - CONTAINER_NAME=d2
    build:
      context: .
    networks:
      - raft-network
    command: "-h=hostfile.txt -t=${PRJ2_TEST_CASE} -d=${PRJ2_DURATION} -v=${PRJ2_VERBOSE} --tfrom=${PRJ2_TFROM} --ttil=${PRJ2_TTIL}"

  raft-client-0:
    image: raft-image
    container_name: c0
    restart: "no"
    environment:
      - CONTAINER_NAME=c0
    build:
      context: .
    networks:
      - raft-network
    entrypoint: "client"
    command: "-hostfile=hostfile.txt -data=datafile.txt -v=${PRJ2_VERBOSE}"
      

networks:
  raft-network:
    name: raft-network
    driver: bridge
