version: "3.5"

services:
  raft-agent-0: 
    image: raft-image
    container_name: r0
    restart: "no"
    environment:
      - CONTAINER_NAME=r0
    build:
      context: .
    networks:
      - raft-network
    volumes:
      - type: bind
        source: ./persistence
        target: /persistence
    entrypoint: "raft"
    command: "-h=hostfile.json -d=${RAFT_DURATION} -v=${RAFT_VERBOSE}"

  raft-agent-1: 
    image: raft-image
    container_name: r1
    restart: "no"
    environment:
      - CONTAINER_NAME=r1
    build:
      context: .
    networks:
      - raft-network
    volumes:
      - type: bind
        source: ./persistence
        target: /persistence
    entrypoint: "raft"
    command: "-h=hostfile.json -d=${RAFT_DURATION} -v=${RAFT_VERBOSE}"

  raft-agent-2: 
    image: raft-image
    container_name: r2
    restart: "no"
    environment:
      - CONTAINER_NAME=r2
    build:
      context: .
    networks:
      - raft-network
    volumes:
      - type: bind
        source: ./persistence
        target: /persistence
    entrypoint: "raft"
    command: "-h=hostfile.json -d=${RAFT_DURATION} -v=${RAFT_VERBOSE}"

  raft-client-0:
    image: raft-image
    container_name: c0
    restart: "no"
    environment:
      - CONTAINER_NAME=c0
    build:
      context: .
    networks:
      - raft-network
    entrypoint: "client"
    command: "-hostfile=hostfile.json -data=datafile.0.txt -v=${RAFT_VERBOSE} -duration=${RAFT_DURATION}"
      
  raft-client-1:
    image: raft-image
    container_name: c1
    restart: "no"
    environment:
      - CONTAINER_NAME=c1
    build:
      context: .
    networks:
      - raft-network
    entrypoint: "client"
    command: "-hostfile=hostfile.json -data=datafile.1.txt -v=${RAFT_VERBOSE} -duration=${RAFT_DURATION}"


networks:
  raft-network:
    name: raft-network
    driver: bridge
